
name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Change this if your default branch is different

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install CSS Minifier
        run: npm install -g clean-css-cli

      - name: Concatenate and Minify CSS
        run: |
          mkdir -p dist
          cat css/*.css > dist/combined.css
          cleancss -o dist/style.min.css dist/combined.css

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: dist

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
